FROM node:18-alpine
WORKDIR /usr/src/app
COPY package.json .
COPY create_env_file.sh .
ADD . /usr/src/app
ARG REACT_APP_BACKEND_URL \
    REACT_APP_API_URL \
    REACT_APP_MAPBOX_TOKEN \
    NODE_ENV
RUN sh create_env_file.sh REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL \
                          REACT_APP_API_URL=$REACT_APP_API_URL \
                          REACT_APP_MAPBOX_TOKEN=$REACT_APP_MAPBOX_TOKEN \
                          NODE_ENV=$NODE_ENV
RUN npm install
CMD ["npm", "run", "start"]
EXPOSE 3000